// <auto-generated />

using System;
using CourseWork.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

namespace CourseWork.Migrations.RestarauntDb
{
    [DbContext(typeof(RestarauntDbContext))]
    internal class RestarauntDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CourseWork.Models.Tables.Customer", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int")
                    .HasAnnotation("SqlServer:ValueGenerationStrategy",
                        SqlServerValueGenerationStrategy.IdentityColumn);

                b.Property<string>("MiddleName")
                    .IsRequired()
                    .HasColumnType("nvarchar(100)")
                    .HasMaxLength(100);

                b.Property<string>("Name")
                    .IsRequired()
                    .HasColumnType("nvarchar(100)")
                    .HasMaxLength(100);

                b.Property<string>("PhoneNumber")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Surname")
                    .IsRequired()
                    .HasColumnType("nvarchar(100)")
                    .HasMaxLength(100);

                b.HasKey("Id");

                b.ToTable("Customers");
            });

            modelBuilder.Entity("CourseWork.Models.Tables.Dish", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int")
                    .HasAnnotation("SqlServer:ValueGenerationStrategy",
                        SqlServerValueGenerationStrategy.IdentityColumn);

                b.Property<int>("CookingTime")
                    .HasColumnType("int");

                b.Property<double>("Cost")
                    .HasColumnType("float");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasColumnType("nvarchar(80)")
                    .HasMaxLength(80);

                b.Property<int>("OrderId")
                    .HasColumnType("int");

                b.HasKey("Id");

                b.HasIndex("OrderId");

                b.ToTable("Dishes");
            });

            modelBuilder.Entity("CourseWork.Models.Tables.DishIngredient", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int")
                    .HasAnnotation("SqlServer:ValueGenerationStrategy",
                        SqlServerValueGenerationStrategy.IdentityColumn);

                b.Property<int>("Count")
                    .HasColumnType("int");

                b.Property<int>("DishId")
                    .HasColumnType("int");

                b.Property<int>("IngredientId")
                    .HasColumnType("int");

                b.HasKey("Id");

                b.HasIndex("DishId");

                b.HasIndex("IngredientId");

                b.ToTable("DishIngredients");
            });

            modelBuilder.Entity("CourseWork.Models.Tables.Employee", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int")
                    .HasAnnotation("SqlServer:ValueGenerationStrategy",
                        SqlServerValueGenerationStrategy.IdentityColumn);

                b.Property<string>("Education")
                    .IsRequired()
                    .HasColumnType("nvarchar(100)")
                    .HasMaxLength(100);

                b.Property<string>("MiddleName")
                    .IsRequired()
                    .HasColumnType("nvarchar(100)")
                    .HasMaxLength(100);

                b.Property<string>("Name")
                    .IsRequired()
                    .HasColumnType("nvarchar(100)")
                    .HasMaxLength(100);

                b.Property<string>("PhoneNumber")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Position")
                    .IsRequired()
                    .HasColumnType("nvarchar(70)")
                    .HasMaxLength(70);

                b.Property<string>("Surname")
                    .IsRequired()
                    .HasColumnType("nvarchar(100)")
                    .HasMaxLength(100);

                b.HasKey("Id");

                b.ToTable("Employees");
            });

            modelBuilder.Entity("CourseWork.Models.Tables.Ingredient", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int")
                    .HasAnnotation("SqlServer:ValueGenerationStrategy",
                        SqlServerValueGenerationStrategy.IdentityColumn);

                b.Property<double>("Cost")
                    .HasColumnType("float");

                b.Property<int>("Count")
                    .HasColumnType("int");

                b.Property<int>("ExpirationDate")
                    .HasColumnType("int");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasColumnType("nvarchar(80)")
                    .HasMaxLength(80);

                b.Property<int>("ProviderId")
                    .HasColumnType("int");

                b.Property<DateTime>("ReleaseDate")
                    .HasColumnType("datetime2");

                b.HasKey("Id");

                b.HasIndex("ProviderId");

                b.ToTable("Ingredients");
            });

            modelBuilder.Entity("CourseWork.Models.Tables.Order", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int")
                    .HasAnnotation("SqlServer:ValueGenerationStrategy",
                        SqlServerValueGenerationStrategy.IdentityColumn);

                b.Property<bool>("Completed")
                    .HasColumnType("bit");

                b.Property<double>("Cost")
                    .HasColumnType("float");

                b.Property<int>("CustomerId")
                    .HasColumnType("int");

                b.Property<DateTime>("Date")
                    .HasColumnType("datetime2");

                b.Property<int>("EmployeeId")
                    .HasColumnType("int");

                b.Property<int>("Payment")
                    .HasColumnType("int");

                b.Property<DateTime>("Time")
                    .HasColumnType("datetime2");

                b.HasKey("Id");

                b.HasIndex("CustomerId");

                b.HasIndex("EmployeeId");

                b.ToTable("Orders");
            });

            modelBuilder.Entity("CourseWork.Models.Tables.Provider", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int")
                    .HasAnnotation("SqlServer:ValueGenerationStrategy",
                        SqlServerValueGenerationStrategy.IdentityColumn);

                b.Property<string>("Address")
                    .IsRequired()
                    .HasColumnType("nvarchar(100)")
                    .HasMaxLength(100);

                b.Property<string>("Name")
                    .IsRequired()
                    .HasColumnType("nvarchar(100)")
                    .HasMaxLength(100);

                b.Property<string>("PhoneNumber")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.HasKey("Id");

                b.ToTable("Providers");
            });

            modelBuilder.Entity("CourseWork.Models.Tables.Dish", b =>
            {
                b.HasOne("CourseWork.Models.Tables.Order", "Order")
                    .WithMany("Dishes")
                    .HasForeignKey("OrderId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });

            modelBuilder.Entity("CourseWork.Models.Tables.DishIngredient", b =>
            {
                b.HasOne("CourseWork.Models.Tables.Dish", "Dish")
                    .WithMany("Ingredients")
                    .HasForeignKey("DishId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("CourseWork.Models.Tables.Ingredient", "Ingredient")
                    .WithMany()
                    .HasForeignKey("IngredientId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });

            modelBuilder.Entity("CourseWork.Models.Tables.Ingredient", b =>
            {
                b.HasOne("CourseWork.Models.Tables.Provider", "Provider")
                    .WithMany("Ingredients")
                    .HasForeignKey("ProviderId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });

            modelBuilder.Entity("CourseWork.Models.Tables.Order", b =>
            {
                b.HasOne("CourseWork.Models.Tables.Customer", "Customer")
                    .WithMany("Orders")
                    .HasForeignKey("CustomerId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("CourseWork.Models.Tables.Employee", "Employee")
                    .WithMany("Orders")
                    .HasForeignKey("EmployeeId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });
#pragma warning restore 612, 618
        }
    }
}